# Generated by Django 5.0.4 on 2026-03-28 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana")),
                ('gender', models.CharField(blank=True, choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Viloyat')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='Tuman/Shahar')),
                ('mahalla', models.CharField(blank=True, max_length=100, verbose_name='Mahalla')),
                ('street', models.CharField(blank=True, max_length=150, verbose_name="Ko'cha")),
                ('house', models.CharField(blank=True, max_length=20, verbose_name='Uy raqami')),
                ('apartment', models.CharField(blank=True, max_length=20, verbose_name='Kvartira')),
                ('floor', models.CharField(blank=True, max_length=10, verbose_name='Qavat')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Pochta indeksi')),
                ('address_note', models.TextField(blank=True, verbose_name="Qo'shimcha yo'nalish")),
                ('balance', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Balans')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('enrolled_at', models.DateField(blank=True, null=True, verbose_name='Qabul sanasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='groups.group', verbose_name='Guruh')),
            ],
            options={
                'verbose_name': 'Talaba',
                'verbose_name_plural': 'Talabalar',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_present', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student')),
            ],
            options={
                'verbose_name': 'Davomat',
                'verbose_name_plural': 'Davomat',
                'ordering': ['-date'],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
