# Generated by Django 5.0.4 on 2026-04-04 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_parent_phones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='excused_absence',
            field=models.BooleanField(default=False, help_text="Sababli: asosli sabab + ustoz roziligi — shu kun to'lov uchun hisoblanadi. Sababsiz kelmagan kunlar uchun to'lov olinmaydi.", verbose_name="Sababli kelmagan (ustoz tasdig'i)"),
        ),
    ]
