# Generated by Django 5.0.4 on 2026-04-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='days',
            field=models.CharField(choices=[('even', 'Juft kunlar (Sesh, Pay, Shan)'), ('odd', 'Toq kunlar (Dush, Chor, Jum)'), ('daily', 'Har kuni')], default='even', max_length=10),
        ),
    ]
